# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.3.4

# Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false